#service-host-url: https://nevex-and-runkeeper.appspot.com

## Remove these!
### https://runkeeper.com/partner/applications/keysAndURLs?clientID=51407cdf5a9344bf8cdeb4cd6bf00e39
nevex-and-runkeeper:
  quotation:
    forismatic-url: http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en
  runkeeper-api:
    base-url: https://api.runkeeper.com
    user-url: ${nevex-and-runkeeper.runkeeper-api.base-url}/user
    profile-url: ${nevex-and-runkeeper.runkeeper-api.base-url}/profile
    team-url: ${nevex-and-runkeeper.runkeeper-api.base-url}/team
    fitness-activities-url: ${nevex-and-runkeeper.runkeeper-api.base-url}/fitnessActivities
  oauth:
    redirect-host: http://localhost:56787
    redirect-url: ${nevex-and-runkeeper.oauth.redirect-host}${server.context-path}/oauthcallback
    register-url: https://runkeeper.com/apps/authorize?client_id=${nevex-and-runkeeper.oauth.client-id}&response_type=code&redirect_uri=${nevex-and-runkeeper.oauth.redirect-url}
    token_url: ${nevex-and-runkeeper.oauth.base-url}/apps/token
    base-url: https://runkeeper.com

server:
  port: 56787
  context-path: /runkeeper

logging:
  file: log/nevex-and-runkeeper.log

spring:
  properties.hibernate.format_sql: true
  thymeleaf:
    cache: false
    prefix: classpath:/static/
    mode: HTML5
    suffix: .html
  datasource:
    url: jdbc:postgresql://localhost:5432/runkeeper
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate #auto-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
