#service-host-url: https://nevex-and-runkeeper.appspot.com

nevex-and-runkeeper:
  quotation:
    forismatic-url: http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en
  runkeeper-api:
    base-url: https://api.runkeeper.com
    user-url: ${nevex-and-runkeeper.runkeeper-api.base-url}/user
    profile-url: ${nevex-and-runkeeper.runkeeper-api.base-url}/profile
    fitness-activities-url: ${nevex-and-runkeeper.runkeeper-api.base-url}/fitnessActivities
  oauth:
    redirect-host: http://localhost:56787
    redirect-url: ${nevex-and-runkeeper.oauth.redirect-host}/register
    register-url: https://runkeeper.com/apps/authorize?client_id=${nevex-and-runkeeper.oauth.client-id}&response_type=code&redirect_uri=${oauth.redirect-url}
    token_url: ${nevex-and-runkeeper.oauth.base-url}/apps/token
    base-url: https://runkeeper.com

server:
  port: 56787
  context-path: /runkeeper

logging:
  file: log/nevex-and-runkeeper.log
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/static/
    mode: HTML5
    suffix: .html
