nevex-and-runkeeper:
  user-id: 52392006
  oauth:
    client-id: 51407cdf5a9344bf8cdeb4cd6bf00e39
    client-secret: 9e7f5d2fe3d24d92a35016732eaa7a48
    code: eyJkYXRhIjp7InIiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvcmVnaXN0ZXIiLCJjIjoiNTE0MDdjZGY1YTkzNDRiZjhjZGViNGNkNmJmMDBlMzkiLCJ0IjoxNDY4OTk3MzU1ODQ1LCJ1Ijo1MjM5MjAwNn0sIm1hYyI6IjFlWXJ4ZWxrQ3RVcm1tTDN3TG5uMEJIekNMZ2s0NmxqOGkvYUJXU2k3WnM9In0
    access-token: 2bd0056be8be4bd48b8cbe835dd85bd3
